"""
Viral CLI Scanner: static log analysis for PII. All processing is local; no data leaves the machine.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import List, Optional

import typer
from unblockllm.pii import PIISpan, find_pii_spans

app = typer.Typer(
    name="unblockllm-scan",
    help="Scan files for PII (EMAIL, PHONE, SSN). All processing is local; no data leaves your machine.",
)


def _read_file(path: Path) -> str:
    """Read file contents. Prefer UTF-8."""
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        typer.echo(f"Error reading file: {e}", err=True)
        raise typer.Exit(1)


def scan_file(path: Path) -> List[PIISpan]:
    """Run regex-based PII detection on file content. No network; fully local."""
    text = _read_file(path)
    return find_pii_spans(text)


def _report_json(spans: List[PIISpan], total_count: int) -> str:
    """Build JSON report. Include counts and types; optionally redact values in report."""
    by_type: dict = {}
    for s in spans:
        by_type.setdefault(s.entity_type, 0)
        by_type[s.entity_type] += 1
    # For shareability, we include counts and types; value can be omitted or hashed in strict mode
    findings = [
        {"type": s.entity_type, "start": s.start, "end": s.end}
        for s in spans
    ]
    return json.dumps(
        {
            "summary": {
                "total_findings": total_count,
                "by_type": by_type,
            },
            "findings": findings,
        },
        indent=2,
    )


def _report_html(spans: List[PIISpan], total_count: int, file_name: str) -> str:
    """Build HTML report for shareable scan result."""
    by_type: dict = {}
    for s in spans:
        by_type.setdefault(s.entity_type, 0)
        by_type[s.entity_type] += 1
    rows = "".join(
        f"<tr><td>{s.entity_type}</td><td>{s.start}</td><td>{s.end}</td></tr>"
        for s in spans
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>unblockllm-scan Report</title></head>
<body>
<h1>Scan Result: {total_count} PII leak(s) found</h1>
<p>File: {file_name}</p>
<p>By type: {json.dumps(by_type)}</p>
<table border="1">
<thead><tr><th>Type</th><th>Start</th><th>End</th></tr></thead>
<tbody>{rows}</tbody>
</table>
<p><em>Generated by unblockllm-scan. All processing was done locally; no data left your machine.</em></p>
</body>
</html>"""


@app.callback(invoke_without_command=True)
def _scan(
    ctx: typer.Context,
    file: Path = typer.Option(..., "--file", "-f", path_type=Path, help="Path to log or text file to scan"),
    output: Optional[Path] = typer.Option(None, "--output", "-o", path_type=Path, help="Write report to this file (default: stdout)"),
    format: str = typer.Option("json", "--format", "-F", help="Report format: json or html"),
) -> None:
    """
    Scan a file for PII (EMAIL, PHONE, SSN). Output is JSON or HTML.
    No data is uploaded; all processing is local.
    """
    if ctx.invoked_subcommand is not None:
        return
    if not file.exists():
        typer.echo(f"File not found: {file}", err=True)
        raise typer.Exit(1)
    spans = scan_file(file)
    total = len(spans)
    if format.lower() == "html":
        report = _report_html(spans, total, str(file.name))
    else:
        report = _report_json(spans, total)
    if output is not None:
        output.write_text(report, encoding="utf-8")
        typer.echo(f"Scan Result: {total} PII leak(s) found. Report written to {output}.", err=False)
    else:
        print(report)
    if total > 0:
        typer.echo(f"Scan Result: {total} PII leak(s) found.", err=True)
    raise typer.Exit(0)


def main() -> None:
    """Entry point for console_scripts (pip install -e .)."""
    app()


if __name__ == "__main__":
    main()
